### ISSUE TITLE
Build database

### ISSUE THREAD

**Issue by cwoodlock** [Kevin-Colm/Project-Gmit#8]
Decide on datatypes, relationships, foreign keys etc. to be used in the database

**Comment by cwoodlock** [comment]
Duplicate entry issue, needs to be fixed.

**Comment by cwoodlock** [comment]
UserType link table needs to be look at and how it might be implemented.

**Comment by kevgleeson78** [comment]
Database issues fixed

**Comment by kevgleeson78** [comment]
All relations are interacting as expected
